ecomm/accounts/urls.py
from django.urls import path
from . import views

# Namespace тодорхойлно
app_name = 'accounts'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('register/', views.register, name='register'),
    path('logout/', views.signout, name='logout'),
]

ecomm/ecomm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from app1 import views as app1_views
from carts import views as cart_views

urlpatterns = [
    path('admin/', admin.site.urls),

    # --- App1 views ---
    path('', app1_views.index, name='index'),
    path('dashboard/', app1_views.dashboard, name='dashboard'),
    path('order-complete/', app1_views.order_complete, name='order_complete'),
    path('place-order/', app1_views.place_order, name='place_order'),
    path('product/<int:product_id>/', app1_views.product_detail, name='product_detail'),
    path('search-result/', app1_views.search_result, name='search_result'),
    path('store/', app1_views.store, name='store'),
    path('submit_review/<int:product_id>/', app1_views.submit_review, name='submit_review'),
    path('store/search/', app1_views.search, name='store_search'),
    path('store/category/<slug:category_slug>/', app1_views.store, name='products_by_category'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),
    # --- Cart views (no carts.urls used) ---s
    path('cart/', cart_views.cart, name='cart'),
    path('add/<int:product_id>/', cart_views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/', cart_views.remove_cart, name='remove_cart'),
    path('remove_item/<int:product_id>/', cart_views.remove_cart_item, name='remove_cart_item'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.BASE_DIR / "static")
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomm/carts/models.py
from django.db import models
from app1.models import Product 

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, unique=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return f"{self.product.product_name} ({self.quantity})"

ecomm/carts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from app1.models import Product
from .models import Cart, CartItem


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        request.session.create()
        cart = request.session.session_key  
    return cart


def add_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart, created = Cart.objects.get_or_create(cart_id=_cart_id(request))

    cart_item, created = CartItem.objects.get_or_create(product=product, cart=cart)
    
    if not created:
        if cart_item.quantity < product.stock:  
            cart_item.quantity += 1
            cart_item.save()
        else:
            from django.contrib import messages
            messages.warning(request, f"Only {product.stock} items available in stock.")
    else:
        if product.stock > 0:
            cart_item.quantity = 1
            cart_item.save()
        else:
            messages.warning(request, "Product is out of stock.")

    return redirect('cart')


def remove_cart(request, product_id):
    cart = get_object_or_404(Cart, cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = get_object_or_404(CartItem, product=product, cart=cart)

    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()

    return redirect('cart')


def remove_cart_item(request, product_id):
    cart = get_object_or_404(Cart, cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = get_object_or_404(CartItem, product=product, cart=cart)
    cart_item.delete()
    return redirect('cart')


def cart(request, total=0, quantity=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for item in cart_items:
            total += item.product.price * item.quantity
            quantity += item.quantity
    except Cart.DoesNotExist:
        cart_items = []

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
    }
    return render(request, 'cart.html', context)

ecomm/templates/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>{% block title %}GreatKart | One of the Biggest Online Shopping Platform{% endblock %}</title>
<link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">

<!-- CSS -->
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/ui.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- JS -->
<script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>

<script type="text/javascript">
$(document).ready(function() {
    // Custom JS here
});
</script>

{% block extra_head %}{% endblock %}
</head>
<body>

<header class="section-header">
<nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom" role="navigation">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarTop4" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTop4">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="languageDropdown" role="button" aria-haspopup="true" aria-expanded="false">Language</a>
          <ul class="dropdown-menu small" aria-labelledby="languageDropdown">
            <li><a class="dropdown-item" href="#">English</a></li>
            <li><a class="dropdown-item" href="#">Arabic</a></li>
            <li><a class="dropdown-item" href="#">Russian</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" id="currencyDropdown" role="button" aria-haspopup="true" aria-expanded="false">USD</a>
          <ul class="dropdown-menu small" aria-labelledby="currencyDropdown">
            <li><a class="dropdown-item" href="#">EUR</a></li>
            <li><a class="dropdown-item" href="#">AED</a></li>
            <li><a class="dropdown-item" href="#">RUBL</a></li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-envelope"></i> Email</a></li>
        <li class="nav-item"><a href="#" class="nav-link"><i class="fa fa-phone"></i> Call us</a></li>
      </ul>
    </div>
  </div>
</nav>

<section class="header-main border-bottom">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-2 col-md-3 col-6">
        <!-- Logo -->
        <a href="/" class="brand-wrap">
            <img class="logo" src="{% static 'images/logo.png' %}" alt="GreatKart Logo">
        </a>
      </div>
      <div class="col-lg col-sm col-md col-6 flex-grow-0">
        <div class="category-wrap dropdown d-inline-block float-right">
          <button type="button" class="btn btn-primary dropdown-toggle" id="categoryDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-bars"></i> All category
          </button>
          <div class="dropdown-menu" aria-labelledby="categoryDropdown">
            {% for cat in links %}
              <a class="dropdown-item" href="{% url 'products_by_category' cat.slug %}">
                {{ cat.category_name }}
              </a>
            {% empty %}
              <span class="dropdown-item">No categories</span>
            {% endfor %}
        </div>
        </div>
      </div>
      <div class="col-auto">
        <a href="{% url 'store' %}" class="btn btn-outline-primary">Store</a>
      </div>
      <div class="col-lg col-md-6 col-sm-12 col">
<form method="GET"
      action="{% if category %}{% url 'products_by_category' category.slug %}{% else %}{% url 'store' %}{% endif %}"
      class="form-inline my-2 my-lg-0">
    <div class="input-group mr-2">
        <input type="text" name="keyword" class="form-control" placeholder="Search products..." value="{{ keyword }}">
    </div>
    <div class="dropdown mr-2">
        <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="priceDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Price range
        </button>
        <div class="dropdown-menu p-3" aria-labelledby="priceDropdown" style="min-width: 250px;">
            <div class="form-row">
                <div class="col">
                    <input type="number" name="min_price" class="form-control" placeholder="Min" value="{{ min_price }}">
                </div>
                <div class="col">
                    <input type="number" name="max_price" class="form-control" placeholder="Max" value="{{ max_price }}">
                </div>
            </div>
            <button type="submit" class="btn btn-primary btn-block mt-2">Apply</button>
        </div>
    </div>
    <button class="btn btn-success" type="submit"><i class="fa fa-search"></i> Search</button>
</form>
      </div>

      <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
        <div class="d-flex justify-content-end mb-3 mb-lg-0">
            <div class="widget-header mr-3">
                {% if request.user.is_authenticated %}
                    <small class="title text-muted">Hello, {{ request.user.first_name }}!</small>
                    <div class="d-flex align-items-center">
                        {% if request.user.account.pro_image %}
                            <img src="{{ request.user.account.pro_image.url }}" alt="Profile" class="rounded-circle" width="35" height="35">
                        {% else %}
                            <i class="fa fa-user-circle fa-2x"></i>
                        {% endif %}
                        <a href="{% url 'accounts:logout' %}" class="ml-2">Log out</a>
                    </div>
                {% else %}
                    <small class="title text-muted">Welcome guest!</small>
                    <div>
                        <a href="{% url 'accounts:signin' %}">Sign in</a> <span class="dark-transp"> | </span>
                        <a href="{% url 'accounts:register' %}">Register</a>
                    </div>
                {% endif %}
            </div>

            <a href="{% url 'cart' %}" class="widget-header pl-3 ml-3">
                <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                <span class="badge badge-pill badge-danger notify">
                    {% if quantity %}
                        {{ quantity }}
                    {% else %}
                        0
                    {% endif %}
                </span>
            </a>
        </div>
      </div>
    </div>
  </div>
</section>
</header>

<main role="main" class="container">
  {% block content %}{% endblock %}
</main>

<footer class="section-footer border-top padding-y">
  <div class="container">
    <p class="float-md-right mb-0">&copy; Copyright 2019 All rights reserved</p>
    <p class="mb-0"><a href="#">Terms and conditions</a></p>
  </div>
</footer>

</body>
</html>

ecomm/templates/cart.html
{% extends "base.html" %}
{% load static %}

{% block title %}Shopping Cart - GreatKart{% endblock %}

{% block content %}
<div class="row">
  <aside class="col-lg-9">
    <div class="card">
      <table class="table table-borderless table-shopping-cart">
        <thead class="text-muted">
          <tr class="small text-uppercase">
            <th scope="col">Product</th>
            <th scope="col" width="120">Quantity</th>
            <th scope="col" width="120">Price</th>
            <th scope="col" class="text-right" width="200"> </th>
          </tr>
        </thead>
        <tbody>
          {% if cart_items %}
            {% for item in cart_items %}
            <tr>
              <td>
                <figure class="itemside align-items-center">
                  <div class="aside">
                    {% if item.product.images %}
                    <img src="/media/{{ item.product.images }}" class="img-sm" alt="{{ item.product.product_name }}">
                  {% else %}
                    <img src="{% static 'images/no-image.png' %}" class="img-sm" alt="No image">
                  {% endif %}
                  
                  
                  </div>
                  <figcaption class="info">
                    <a href="{% url 'product_detail' item.product.id %}" class="title text-dark">{{ item.product.product_name }}</a>
                    <p class="text-muted small">Price: ${{ item.product.price|floatformat:2 }}</p>
                  </figcaption>
                </figure>
              </td>
              <td>
                <div class="col">
                  <div class="input-group input-spinner">
                    <div class="input-group-prepend">
                      <a class="btn btn-light" href="{% url 'remove_cart' item.product.id %}"><i class="fa fa-minus"></i></a>
                    </div>
                    <input type="text" class="form-control text-center" value="{{ item.quantity }}" readonly>
                    <div class="input-group-append">
                      <a class="btn btn-light" href="{% url 'add_cart' item.product.id %}"><i class="fa fa-plus"></i></a>
                    </div>
                  </div>
                </div>
              </td>
              <td>
                <div class="price-wrap">
                  <var class="price">${{ item.sub_total|floatformat:2 }}</var>
                  <small class="text-muted">${{ item.product.price|floatformat:2 }} each</small>
                </div>
              </td>
              <td class="text-right">
                <a href="{% url 'remove_cart_item' item.product.id %}" class="btn btn-danger">Remove</a>
              </td>
            </tr>
            {% endfor %}
          {% else %}
            <tr>
              <td colspan="4" class="text-center text-muted">Your cart is empty.</td>
            </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
  </aside>

  <aside class="col-lg-3">
    <div class="card">
      <div class="card-body">
        <dl class="dlist-align">
          <dt>Total items:</dt>
          <dd class="text-right">{{ quantity }}</dd>
        </dl>
        <dl class="dlist-align">
          <dt>Total price:</dt>
          <dd class="text-right">${{ total|floatformat:2 }}</dd>
        </dl>
        <hr>
        <p class="text-center mb-3">
          {% if cart_items %}
            {% with first_item=cart_items.0 %}
              {% if first_item.product.image %}
                <img src="/media/{{ first_item.product.image }}" class="img-sm" alt="{{ first_item.product.product_name }}">
              {% else %}
                <img src="{% static 'images/no-image.png' %}" class="img-sm" alt="No image">
              {% endif %}
            {% endwith %}
          {% else %}
            <img src="{% static 'images/no-image.png' %}" class="img-sm" alt="No image">
          {% endif %}
        </p>
        <a href="{% url 'place_order' %}" class="btn btn-primary btn-block"> Place order </a>
        <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
      </div>
    </div>
  </aside>
</div>
{% endblock %}

ecomm/templates/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block title %}Order Details - GreatKart{% endblock %}

{% block content %}
<section class="section-conten padding-y bg">
  <div class="container">
    <div class="row">
      <aside class="col-md-3">
        <!-- SIDEBAR -->
        <ul class="list-group">
          <a class="list-group-item active" href="#"> My order history </a>
          <a class="list-group-item" href="#"> Transactions </a>
          <a class="list-group-item" href="#"> Return and refunds </a>
          <a class="list-group-item" href="#">Settings </a>
          <a class="list-group-item" href="#"> My Selling Items </a>
          <a class="list-group-item" href="#"> Received orders </a>
        </ul>
        <br>
        <a class="btn btn-light btn-block" href="#"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a>
        <!-- SIDEBAR END -->
      </aside>
      <main class="col-md-9">
        <article class="card">
          <header class="card-header">
            <strong class="d-inline-block mr-3">Order ID: 6123456789</strong>
            <span>Order Date: 16 December 2018</span>
          </header>
          <div class="card-body">
            <div class="row">
              <div class="col-md-8">
                <h6 class="text-muted">Delivery to</h6>
                <p>
                  Michael Jackson <br>
                  Phone +1234567890 Email: myname@pixsellz.com <br>
                  Location: Home number, Building name, Street 123,  Tashkent, UZB <br>
                  P.O. Box: 100123
                </p>
              </div>
              <div class="col-md-4">
                <h6 class="text-muted">Payment</h6>
                <span class="text-success">
                  <i class="fab fa-lg fa-cc-visa"></i>
                  Visa  **** 4216
                </span>
                <p>Subtotal: $356 <br>
                  Shipping fee:  $56 <br>
                  <span class="b">Total:  $456 </span>
                </p>
              </div>
            </div> <!-- row.// -->
          </div> <!-- card-body .// -->
          <div class="table-responsive">
            <table class="table table-hover">
              <tr>
                <td width="65">
                  <img src="{% static 'images/items/1.jpg' %}" class="img-xs border" alt="Product 1">
                </td>
                <td>
                  <p class="title mb-0">Product name goes here </p>
                  <var class="price text-muted">USD 145</var>
                </td>
                <td> Seller <br> Nike clothing </td>
                <td width="250"> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
              </tr>
              <tr>
                <td>
                  <img src="{% static 'images/items/2.jpg' %}" class="img-xs border" alt="Product 2">
                </td>
                <td>
                  <p class="title mb-0">Another name goes here </p>
                  <var class="price text-muted">USD 15</var>
                </td>
                <td> Seller <br> ABC shop </td>
                <td> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
              </tr>
              <tr>
                <td>
                  <img src="{% static 'images/items/3.jpg' %}" class="img-xs border" alt="Product 3">
                </td>
                <td>
                  <p class="title mb-0">The name of the product goes here </p>
                  <var class="price text-muted">USD 145</var>
                </td>
                <td> Seller <br> Wallmart </td>
                <td> <a href="#" class="btn btn-outline-primary">Track order</a> <a href="#" class="btn btn-light"> Details </a> </td>
              </tr>
            </table>
          </div> <!-- table-responsive .end// -->
        </article> <!-- order-group.// -->
      </main>
    </div> <!-- row.// -->
  </div>
</section>
{% endblock %}

ecomm/templates/index.html
{% extends "base.html" %}
{% block title %}Shopping Cart - GreatKart ({{ product_count }} products){% endblock %}

{% block content %}
<div class="form-inline">
    <span class="mr-md-auto">Latest {{ products|length }} products </span>
</div>

<div class="row">
    {% for product in products %}
    <div class="col-md-3 mb-4">
        <div class="card card-product-grid h-100">
            <a href="{% url 'product_detail' product.data.0 %}">
                <div class="img-wrap">
                    <img src="/media/{{ product.data.5 }}" alt="{{ product.data.1 }}" class="img-fluid">
                </div>
                <figcaption class="info-wrap p-2 text-center">
                    <h6 class="title mb-1">{{ product.data.1 }}</h6>

                    <!-- Ratings above price -->
                    <div class="rating text-warning mb-1">
                        {% for _ in product.full_stars %}
                            <i class="fa fa-star"></i>
                        {% endfor %}
                        {% if product.half_star %}
                            <i class="fa fa-star-half-alt"></i>
                        {% endif %}
                        {% for _ in product.empty_stars %}
                            <i class="fa fa-star-o"></i>
                        {% endfor %}
                        <span class="text-muted">({{ product.average_rating|floatformat:1 }})</span>
                    </div>

                    <div class="price text-primary">${{ product.data.4|floatformat:2 }}</div>
                </figcaption>
            </a>
        </div>
    </div>
    {% empty %}
    <p class="text-muted">No products available.</p>
    {% endfor %}
</div>
{% endblock %}

ecomm/templates/order_complete.html
{% load static %}

<div class="container" style="margin-top: 50px;">
    <center>
        <i class="fas fa-check-circle" style="font-size: 72px; margin-bottom: 20px; color: #28A745;"></i>
    </center>
    <h2 class="text-center">Payment Successful</h2>
    <br>
    <div class="text-center">
        <a href="{% url 'store' %}" class="btn btn-success">Shop more</a>
    </div>
</div>

<div class="container" style="margin: 0 auto; width: 50%; padding: 50px; background: #f1f1f1; margin-top: 50px; margin-bottom: 50px;">
    <div class="row invoice row-printable">
        <div class="col-md-12">
            <div class="panel panel-default plain" id="dash_0">
                <div class="panel-body p30">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="invoice-logo">
                                <img src="{% static 'images/logo.png' %}" alt="Invoice logo" style="max-height: 40px;">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="invoice-from">
                                <ul class="list-unstyled text-right">
                                    <li><strong>Invoiced To</strong></li>
                                    <li>Jakob Smith</li>
                                    <li>Roupark 37</li>
                                    <li>New York, NY, 2014</li>
                                    <li>USA</li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="invoice-details mt25">
                                <div class="well">
                                    <ul class="list-unstyled mb0">
                                        <li><strong>Order</strong> #</li>
                                        <li><strong>Transaction</strong> #</li>
                                        <li><strong>Order Date:</strong> Monday, October 10th, 2015</li>
                                        <li><strong>Status:</strong> PAID</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="invoice-items">
                                <div class="table-responsive" tabindex="0" style="overflow: hidden; outline: none;">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th class="per70 text-center">Description</th>
                                                <th class="per5 text-center">Qty</th>
                                                <th class="per25 text-center">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>1024MB Cloud 2.0 Server - elisium.dynamic.com (12/04/2014 - 01/03/2015)</td>
                                                <td class="text-center">1</td>
                                                <td class="text-center">$25.00 USD</td>
                                            </tr>
                                            <tr>
                                                <td>Logo design</td>
                                                <td class="text-center">1</td>
                                                <td class="text-center">$200.00 USD</td>
                                            </tr>
                                            <tr>
                                                <td>Backup - 1024MB Cloud 2.0 Server - elisium.dynamic.com</td>
                                                <td class="text-center">12</td>
                                                <td class="text-center">$12.00 USD</td>
                                            </tr>
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th colspan="2" class="text-right">Sub Total:</th>
                                                <th class="text-center">$237.00 USD</th>
                                            </tr>
                                            <tr>
                                                <th colspan="2" class="text-right">Tax:</th>
                                                <th class="text-center">$47.40 USD</th>
                                            </tr>
                                            <tr>
                                                <th colspan="2" class="text-right">Grand Total:</th>
                                                <th class="text-center">$284.40 USD</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <div class="invoice-footer mt25">
                                <p class="text-center">Thank you for shopping with us!</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ecomm/templates/product-detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ product.product_name }} | GreatKart{% endblock %}

{% block content %}
<section class="section-content padding-y bg">
  <div class="container">

    <div class="card">
      <div class="row no-gutters">

        <!-- Product Image -->
        <aside class="col-md-6">
          <article class="gallery-wrap"> 
            <div class="img-big-wrap">
              {% if product.images %}
              <img src="{{ product.images.url }}" alt="{{ product.product_name }}" class="img-fluid">
              {% else %}
              <img src="{% static 'images/no-image.png' %}" alt="No image available" class="img-fluid">
              {% endif %}
            </div>
          </article>
        </aside>

        <!-- Product Info -->
        <main class="col-md-6 border-left">
          <article class="content-body">
            <h2 class="title">{{ product.product_name }}</h2>

            <div class="mb-3"> 
              <var class="price h4">${{ product.price|floatformat:2 }}</var> 
            </div> 

            <p>{{ product.description }}</p>
            <p><strong>Stock:</strong> {{ product.stock }}</p>
            <p><strong>Category ID:</strong> {{ product.category_id }}</p>

            <hr>

              <h4>Average rating: 
                {% for _ in full_stars %}
                  <i class="fas fa-star text-warning"></i>
                {% endfor %}

                {% if half_star %}
                  <i class="fas fa-star-half-alt text-warning"></i>
                {% endif %}

                {% for _ in empty_stars %}
                  <i class="far fa-star text-warning"></i>
                {% endfor %}

                ({{ average_rating }}/5)
              </h4>


            <a href="{% url 'add_cart' product.id %}" class="btn btn-block btn-success mt-2">
              <span class="text">Add to cart</span> 
              <i class="fas fa-shopping-cart"></i>  
            </a>
          </article>
        </main>
      </div>
    </div>


    <!-- REVIEW FORM -->
    <hr>
    <h4>Write your review</h4>

    <form method="POST" action="{% url 'submit_review' product.id %}">
        {% csrf_token %}

        Rate this product:
        <select name="rate" class="form-control w-25">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select>

        <br>

        <input type="text"
               class="form-control"
               placeholder="Enter title"
               name="title">

        <br>

        <textarea name="review"
                  class="form-control"
                  placeholder="Enter review"></textarea>

        <br>

        {% if user.is_authenticated %}
            <input type="submit" value="Submit review" class="btn btn-primary">
        {% else %}
            <p>You must <a href="{% url 'accounts:signin' %}">login</a> first</p>
        {% endif %}
    </form>



    <!-- REVIEW LIST -->
    <hr>
    <h4>Customer Reviews</h4>

    {% for c in comments %}
    <div class="card p-3 mt-3">
        <h5>{{ c.title }} — ⭐ {{ c.rating }}/5</h5>
        <p>{{ c.review }}</p>
        <small>By {{ c.user.username }} on {{ c.created_date }}</small>
    </div>
    {% empty %}
    <p>No reviews yet.</p>
    {% endfor %}

  </div>
</section>
{% endblock %}